name: pawdiary
description: "Evcil hayvan bakım ve takip uygulaması"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # State Management
  provider: ^6.1.1
  
  # UI & UX
  flutter_localizations:
    sdk: flutter
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # Image Handling
  image_picker: ^1.0.4
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  # Path
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - lib/l10n/
  
  # Fonts (eğer özel font kullanmak istiyorsanız)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700